container:
    image: fedora:24

packages:
    - git
    - gcc
    - python3-tox
    - redhat-rpm-config
    - openssl-devel

tests:
    - python3-tox

timeout: 5m

artifacts:
    - build/cover/
    - nosetests.html
